import type {
  AgentBudgetSettings,
  AutomationSettings,
  BackupInfo,
  DigestItem,
  KnowledgeNodeItem,
  LearningGoalItem,
  LearningResourceItem,
  LessonPlan,
  LogItem,
  NewsItem,
  NotificationItem,
  Preferences,
  QuizItemView,
  RuntimeInfo,
  RuntimeProbe,
  TaskItem,
  WatchFieldItem,
  WatchSourceItem,
} from "./api";
import { addDays, formatDate } from "./date";

const today = formatDate(new Date());
const at = (date: string, time: string) => `${date}T${time}:00`;

const tasks: TaskItem[] = [
  {
    id: "demo-task-1",
    seriesId: null,
    occurrenceKey: null,
    title: "完成产品发布说明与演示截图",
    notes: "聚焦用户价值，不堆砌技术术语。",
    priority: "p0",
    estimatedMinutes: 75,
    completionCriteria: "完成中文版手册并通过链接检查",
    status: "in_progress",
    timeMode: "floating",
    scheduledDate: today,
    scheduledLocal: at(today, "09:30"),
    scheduledUtc: null,
    tzid: null,
    dstAdjusted: false,
    isVirtual: false,
    version: 2,
    seriesVersion: null,
    progressPercent: 45,
    progressNote: "核心结构已完成",
    blockedReason: null,
    snoozedUntilUtc: null,
  },
  {
    id: "demo-task-2",
    seriesId: "demo-series-1",
    occurrenceKey: `floating:${today}T14:00:00`,
    title: "深度学习：阅读 Transformer 综述",
    notes: null,
    priority: "p1",
    estimatedMinutes: 50,
    completionCriteria: "写下三个关键结论",
    status: "todo",
    timeMode: "floating",
    scheduledDate: today,
    scheduledLocal: at(today, "14:00"),
    scheduledUtc: null,
    tzid: null,
    dstAdjusted: false,
    isVirtual: true,
    version: 0,
    seriesVersion: 1,
    progressPercent: null,
    progressNote: null,
    blockedReason: null,
    snoozedUntilUtc: null,
  },
  {
    id: "demo-task-3",
    seriesId: null,
    occurrenceKey: null,
    title: "整理本周行业动态并标记高价值来源",
    notes: null,
    priority: "p1",
    estimatedMinutes: 35,
    completionCriteria: "保留不超过五条可行动信息",
    status: "todo",
    timeMode: "floating",
    scheduledDate: today,
    scheduledLocal: at(today, "17:15"),
    scheduledUtc: null,
    tzid: null,
    dstAdjusted: false,
    isVirtual: false,
    version: 1,
    seriesVersion: null,
    progressPercent: null,
    progressNote: null,
    blockedReason: null,
    snoozedUntilUtc: null,
  },
  {
    id: "demo-task-4",
    seriesId: null,
    occurrenceKey: null,
    title: "30 分钟力量训练",
    notes: null,
    priority: "p2",
    estimatedMinutes: 30,
    completionCriteria: null,
    status: "completed",
    timeMode: "floating",
    scheduledDate: addDays(today, -1),
    scheduledLocal: at(addDays(today, -1), "19:00"),
    scheduledUtc: null,
    tzid: null,
    dstAdjusted: false,
    isVirtual: false,
    version: 3,
    seriesVersion: null,
    progressPercent: 100,
    progressNote: null,
    blockedReason: null,
    snoozedUntilUtc: null,
  },
  {
    id: "demo-task-5",
    seriesId: null,
    occurrenceKey: null,
    title: "复盘本周目标并安排下周重点",
    notes: null,
    priority: "p2",
    estimatedMinutes: 40,
    completionCriteria: null,
    status: "todo",
    timeMode: "all_day",
    scheduledDate: addDays(today, 2),
    scheduledLocal: null,
    scheduledUtc: null,
    tzid: null,
    dstAdjusted: false,
    isVirtual: false,
    version: 1,
    seriesVersion: null,
    progressPercent: null,
    progressNote: null,
    blockedReason: null,
    snoozedUntilUtc: null,
  },
];

const preferences: Preferences = {
  theme: "light",
  weekStartsOn: "monday",
  clockFormat: "24h",
  closeToTray: true,
  notificationsEnabled: true,
  appTimezone: "Asia/Shanghai",
};

const notifications: NotificationItem[] = [
  {
    id: "demo-notification-1",
    reminderId: "demo-reminder-1",
    taskId: "demo-task-2",
    title: "深度学习：阅读 Transformer 综述",
    scheduledForUtc: `${today}T06:00:00Z`,
    deliveredAtUtc: `${today}T06:00:01Z`,
    taskStatus: "todo",
    isRead: false,
  },
];

const digests: DigestItem[] = [
  {
    id: "demo-digest-morning",
    digestType: "morning",
    periodStart: today,
    periodEnd: today,
    content: {
      headline: "今天只抓一件事：完成发布材料，让成果真正被看见。",
      priorities: [
        { title: "完成产品发布说明与演示截图", firstStep: "先确认手册目录和五张核心截图" },
        { title: "深度学习：阅读 Transformer 综述", firstStep: "用 25 分钟提取三条主线" },
        { title: "整理本周行业动态", firstStep: "只保留能改变下一步行动的信息" },
      ],
      statistics: { planned: 3, completed: 0, blocked: 0, canceled: 0 },
    },
    generator: "local-rules",
    createdAtUtc: `${today}T00:00:00Z`,
  },
];

const watchFields: WatchFieldItem[] = [
  {
    id: "demo-field-ai",
    name: "AI 与开发工具",
    description: "追踪模型能力、开发平台和开源生态中的重要变化。",
    includeTerms: ["AI", "developer tools", "open source"],
    excludeTerms: [],
    regions: ["global"],
    languages: ["zh-CN", "en-US"],
    maxItems: 8,
    readingMinutes: 15,
    relevanceWeight: 0.4,
    recencyWeight: 0.25,
    authorityWeight: 0.25,
    heatWeight: 0.1,
    breakingAlerts: true,
    enabled: true,
    sourceCount: 3,
    lastSuccessAtUtc: `${today}T01:30:00Z`,
  },
  {
    id: "demo-field-health",
    name: "脑健康与睡眠",
    description: "关注高质量研究与临床指南更新。",
    includeTerms: ["sleep", "brain health"],
    excludeTerms: [],
    regions: ["global"],
    languages: ["zh-CN", "en-US"],
    maxItems: 5,
    readingMinutes: 10,
    relevanceWeight: 0.45,
    recencyWeight: 0.2,
    authorityWeight: 0.3,
    heatWeight: 0.05,
    breakingAlerts: false,
    enabled: true,
    sourceCount: 2,
    lastSuccessAtUtc: `${today}T01:30:00Z`,
  },
];

const watchSources: WatchSourceItem[] = [
  {
    id: "demo-source-1",
    fieldId: "demo-field-ai",
    name: "OpenAI News",
    url: "https://openai.com/news/rss.xml",
    sourceType: "rss",
    selector: null,
    authority: 0.95,
    enabled: true,
    lastSuccessAtUtc: `${today}T01:30:00Z`,
    lastError: null,
    sortOrder: 0,
  },
  {
    id: "demo-source-2",
    fieldId: "demo-field-ai",
    name: "Rust Blog",
    url: "https://blog.rust-lang.org/feed.xml",
    sourceType: "rss",
    selector: null,
    authority: 0.9,
    enabled: true,
    lastSuccessAtUtc: `${today}T01:30:00Z`,
    lastError: null,
    sortOrder: 1,
  },
];

const news: NewsItem[] = [
  {
    id: "demo-news-1",
    fieldId: "demo-field-ai",
    sourceId: "demo-source-1",
    sourceName: "OpenAI News",
    canonicalUrl: "https://openai.com/news/",
    title: "更可靠的智能体工作流正在进入桌面工具",
    summary: "新的工具调用和隔离机制让长任务更容易审计、恢复和控制成本。",
    publishedAtUtc: `${today}T00:20:00Z`,
    informationKind: "official_statement",
    score: 0.94,
    isRead: false,
    isSaved: true,
    feedback: null,
    uncertainty: null,
  },
  {
    id: "demo-news-2",
    fieldId: "demo-field-ai",
    sourceId: "demo-source-2",
    sourceName: "Rust Blog",
    canonicalUrl: "https://blog.rust-lang.org/",
    title: "Rust 工具链继续改善 Windows 桌面开发体验",
    summary: "围绕构建速度、诊断信息和供应链可见性的改进值得桌面团队关注。",
    publishedAtUtc: `${addDays(today, -1)}T09:10:00Z`,
    informationKind: "analysis_inference",
    score: 0.86,
    isRead: false,
    isSaved: false,
    feedback: null,
    uncertainty: "影响范围仍需结合项目依赖版本确认。",
  },
  {
    id: "demo-news-3",
    fieldId: "demo-field-ai",
    sourceId: "demo-source-1",
    sourceName: "OpenAI News",
    canonicalUrl: "https://openai.com/news/",
    title: "本地优先应用把隐私与可恢复性放回核心位置",
    summary: "本地数据库、显式审批和最小权限接口正在成为个人效率软件的新基线。",
    publishedAtUtc: `${addDays(today, -2)}T03:45:00Z`,
    informationKind: "media_report",
    score: 0.82,
    isRead: true,
    isSaved: false,
    feedback: null,
    uncertainty: null,
  },
];

const learningGoals: LearningGoalItem[] = [
  {
    id: "demo-goal-1",
    name: "系统掌握现代 AI 工程",
    purpose: "能够独立设计可靠、可评估的智能体产品。",
    currentLevel: "能完成基础模型调用",
    targetLevel: "能设计生产级工作流",
    targetDate: addDays(today, 90),
    weeklyMinutes: 240,
    dailyMinutes: 40,
    language: "zh-CN",
    resourcePreferences: ["官方文档", "高质量课程", "动手项目"],
    budgetMode: "free_first",
    autoAddLessons: false,
    status: "active",
    nodeCount: 3,
    dueCount: 1,
  },
];

const knowledgeNodes: KnowledgeNodeItem[] = [
  {
    id: "demo-node-1",
    goalId: "demo-goal-1",
    name: "提示与结构化输出",
    plainExplanation: "让模型稳定地产生可验证、可被程序处理的结果。",
    stageOutcome: "能定义 JSON Schema 并处理失败回退",
    estimatedMinutes: 120,
    prerequisiteIds: [],
    status: "review_due",
    masteryScore: 72,
    quizCount: 4,
    dueCount: 1,
  },
  {
    id: "demo-node-2",
    goalId: "demo-goal-1",
    name: "工具调用与权限边界",
    plainExplanation: "把模型建议与真实世界操作分离，并为写操作设置审批。",
    stageOutcome: "能设计最小权限工具注册表",
    estimatedMinutes: 180,
    prerequisiteIds: ["demo-node-1"],
    status: "learning",
    masteryScore: 46,
    quizCount: 2,
    dueCount: 0,
  },
  {
    id: "demo-node-3",
    goalId: "demo-goal-1",
    name: "评估与可观察性",
    plainExplanation: "用固定样本和结构化日志衡量质量、延迟与失败模式。",
    stageOutcome: "建立一套可重复的回归评估",
    estimatedMinutes: 210,
    prerequisiteIds: ["demo-node-2"],
    status: "not_started",
    masteryScore: 18,
    quizCount: 0,
    dueCount: 0,
  },
];

const resources: LearningResourceItem[] = [
  {
    id: "demo-resource-1",
    nodeId: "demo-node-1",
    title: "结构化输出实践指南",
    author: "PGA Demo",
    publishedDate: today,
    resourceType: "guide",
    durationMinutes: 35,
    difficulty: "intermediate",
    cost: "free",
    versionFit: "2026",
    url: "https://example.com/structured-output",
    recommendationReason: "与当前节点直接相关，适合边读边实践。",
  },
];

const quizzes: QuizItemView[] = [
  {
    id: "demo-quiz-1",
    nodeId: "demo-node-1",
    nodeName: "提示与结构化输出",
    questionType: "single_choice",
    prompt: "哪种方法最适合约束机器可读输出？",
    options: ["仅增加提示长度", "定义并验证 JSON Schema", "提高温度", "重复调用三次"],
    explanationAfterSubmit: null,
    difficulty: 2,
    dueUtc: `${today}T00:00:00Z`,
    isDue: true,
  },
];

const lessonPlans: LessonPlan[] = [
  {
    id: "demo-plan-1",
    planDate: today,
    goalId: "demo-goal-1",
    goalName: "系统掌握现代 AI 工程",
    budgetMinutes: 40,
    plannedMinutes: 35,
    taskLoad: "normal",
    status: "suggested",
    version: 1,
    items: [
      {
        id: "demo-plan-item-1",
        nodeId: "demo-node-1",
        itemKind: "review",
        title: "复习结构化输出的失败处理",
        minutes: 10,
        sortOrder: 0,
      },
      {
        id: "demo-plan-item-2",
        nodeId: "demo-node-2",
        itemKind: "learn",
        title: "学习最小权限工具设计",
        minutes: 25,
        sortOrder: 1,
      },
    ],
  },
];

const runtimeInfo: RuntimeInfo = {
  appVersion: "1.1.1",
  dataDirectory: "%APPDATA%\\org.personal-growth-assistant.desktop",
  databaseEngine: "SQLite",
  recurrenceEngine: "RRule.rs",
  timezoneDatabase: "IANA",
  agentBridge: "MCP SDK v2 sidecar",
};

const runtimeProbe: RuntimeProbe = {
  provider: "codex",
  state: "ready",
  version: "codex 1.0",
  message: "隔离 Runtime 已登录，可以生成 Codex 增强建议。",
  isolatedHome: "%LOCALAPPDATA%\\PersonalGrowthAssistant\\codex-home",
  capabilities: ["structured-output", "scoped-mcp", "cancel", "timeout"],
};

const budget: AgentBudgetSettings = {
  enabled: true,
  dailyRunLimit: 2,
  monthlyRunLimit: 40,
  budgetMode: "saving",
};

const automation: AutomationSettings = {
  morningEnabled: true,
  morningTime: "08:00",
  eveningEnabled: true,
  eveningTime: "21:30",
  weeklyEnabled: true,
  weeklyWeekday: 6,
  weeklyTime: "20:30",
  intelligenceEnabled: true,
  intelligenceIntervalHours: 6,
  lessonEnabled: true,
  lessonTime: "07:45",
};

const backups: BackupInfo[] = [
  { name: "daily-demo.sqlite3", createdAtUtc: `${today}T00:05:00Z`, sizeBytes: 630784 },
];

const failures: LogItem[] = [];

const values: Record<string, unknown> = {
  list_tasks: tasks,
  list_notifications: notifications,
  get_preferences: preferences,
  get_startup_enabled: true,
  list_backups: backups,
  list_trash: [],
  third_party_notices: "Documentation demo",
  list_watch_fields: watchFields,
  list_watch_sources: watchSources,
  list_news: news,
  list_learning_goals: learningGoals,
  list_knowledge_nodes: knowledgeNodes,
  list_learning_resources: resources,
  list_quiz_items: quizzes,
  probe_agent_runtime: runtimeProbe,
  get_agent_budget: budget,
  get_automation_settings: automation,
  list_digests: digests,
  list_daily_lessons: lessonPlans,
  list_recent_failures: failures,
  runtime_info: runtimeInfo,
};

export function installDocsDemoBridge() {
  localStorage.setItem("pga-onboarding", "done");
  localStorage.setItem("pga-supervisor-onboarding", "done");
  localStorage.setItem("pga-tutor-onboarding", "done");
  localStorage.setItem("pga-language", "zh-CN");
  localStorage.setItem("pga-theme", "light");

  const target = window as unknown as {
    __TAURI_INTERNALS__: { invoke: (command: string) => Promise<unknown> };
  };
  target.__TAURI_INTERNALS__ = {
    invoke: async (command: string) => values[command] ?? null,
  };
}
